### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by pcolmer** [Firenza/secrets-to-env#3]
Hi

I'm getting this warning when I use your Action:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: Firenza/secrets-to-env

**Comment by Firenza** [comment]
Working on it now!

**Comment by Firenza** [comment]
Ok done
